# Generated by Django 4.1.2 on 2022-10-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='number_of_booked_seats',
        ),
        migrations.AddField(
            model_name='reservation',
            name='seats',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
