# Generated by Django 4.1.2 on 2022-10-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_remove_event_number_of_booked_seats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
