# Generated by Django 4.1.2 on 2022-10-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0013_alter_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='number_of_seats',
            field=models.PositiveIntegerField(),
        ),
    ]
