# Generated by Django 4.1.2 on 2022-10-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0017_alter_event_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='seats',
            field=models.PositiveIntegerField(),
        ),
    ]
