# Generated by Django 4.1.2 on 2022-10-30 13:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0019_alter_reservation_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='planner.event'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='seats',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Minimum reservation seats is 1 seat.')]),
        ),
    ]
